Better "UUID mismatch on reserialized node" message
- Changed the "UUID mismatch on reserialized node" error message to be more informative.
- Added a unit test to make sure this works (thanks Claude)

Example output:

    File "/Users/kimmy/krnel/krnel-client-library/src/krnel/graph/op_spec.py", line 596, in graph_deserialize
        result = [_construct_op(uuid) for uuid in data["outputs"]]
                ~~~~~~~~~~~~~^^^^^^
    File "/Users/kimmy/krnel/krnel-client-library/src/krnel/graph/op_spec.py", line 544, in _construct_op
        node_data[name] = _construct_op(node_data[name])
                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
    File "/Users/kimmy/krnel/krnel-client-library/src/krnel/graph/op_spec.py", line 544, in _construct_op
        node_data[name] = _construct_op(node_data[name])
                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
    File "/Users/kimmy/krnel/krnel-client-library/src/krnel/graph/op_spec.py", line 544, in _construct_op
        node_data[name] = _construct_op(node_data[name])
                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
    File "/Users/kimmy/krnel/krnel-client-library/src/krnel/graph/op_spec.py", line 592, in _construct_op
        raise UUIDMismatchError(original_node_data[uuid], uuid, uuid_to_op[uuid])
    krnel.graph.op_spec.UUIDMismatchError: UUID mismatch on reserialized node:
        --- Previous (saved) LLMLayerActivationsOp_e8ff45aefcc1da0697a768d103fa7906290bf8699e441570bb7a92685ba8b81e
        +++ New (reconstructed) LLMLayerActivationsOp_b5429e7241d9e98fe98bf6825fe119a6e7ec86d4fd25c50d271538ea483003b8
        @@ -8,5 +8,6 @@
        "max_length": 2048,
        "dtype": "float16",
        "device": "auto",
        -  "torch_compile": false
        +  "torch_compile": false,
        +  "something": "foobar"
        }
    The definition of LLMLayerActivationsOp has changed since the graph was serialized (fields added/removed, default values changed, etc). If you're in a notebook, try restarting your Python process to clear any stale class definitions.